### ISSUE TITLE
[PE-D][Tester A] The title of the application when launching GUI should be the name of the application

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F10-1/tp#174] opened 2024-11-08 15:16 UTC
![image.png](https://raw.githubusercontent.com/awdse22/ped/main/files/ab9437e5-4523-4ec3-b19b-179190eddac8.png)

Currently the name of the application at the top left corner of the GUI states `Address App`, which is the same as the original AB3. This can be changed to `Supply Central` so it's less confusing for the user.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: awdse22/ped#1

**Comment by thenosewizard** [comment] 2024-11-09 06:24
Can be fixed

**Comment by jialegitgud** [comment] 2024-11-09 06:30
Duplicate of #192

**Comment by jialegitgud** [comment] 2024-11-10 11:59
Resolved.

**Closed by jialegitgud** 2024-11-10 11:59 UTC
